WebApplication3/Models/Product.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel;
using System.Linq;
using System.Web;

namespace WebApplication3.Models
{
    public class Product
    {
        [DisplayName("Mã sản phẩm")]
        public string Id { get; set; }


        [DisplayName("Tên sản phẩm")]
        public string Name { get; set; }

        [DisplayName("Ảnh sản phẩm")]
        public string Image { get; set; }

        [DisplayName("Giá")]
        public float Price { get; set; }

        [DisplayName("Giá Sale")]
        public float PriceSale { get; set; }
        [DisplayName("Sale")]
        public int Sale { get; set; }
        [DisplayName("Số sao")]
        public int Star { get; set; }
    }
}

WebApplication3/Models/StudentInfo.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace WebApplication3.Models
{
    public class StudentInfo
    {
        [DisplayName("Mã sinh viên")]
        public string Id { get; set; }

        [DisplayName("Mật khẩu"), DataType(DataType.Password)]
        public string Pwd { get; set; }

        [DisplayName("Họ tên")]
        public string Name { get; set; }

        [DisplayName("Ảnh đại diện")]
        public string Avatar { get; set; }

        [DisplayName("Ngay sinh")]
        public string BirthDay { get; set; }
        
        [DisplayName("Điểm sinh viên")]
        public string Mark { get; set; }
        [DisplayName("Ghi chu"), DataType(DataType.MultilineText)]
        public string Note { get; set; }
        
    }
}

WebApplication3/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebApplication3.Controllers
{
    public class HomeController : Controller
    {
        static List<Models.StudentInfo> lst = new List<Models.StudentInfo>();
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About(int id)
        {
            ViewBag.Message = "Your application description page."+id;

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
        public ActionResult Test()
        {

            return View();
        }
        public ActionResult Login()
        {
            var listRole =new List<dynamic>();
            listRole.Add(new { id = 1, name = "Quản trị" });
            listRole.Add(new { id = 2, name = "người dùng" });
            ViewBag.Roles=new SelectList(listRole, "id", "name"); // danh sách value member - display member
            return View();
        }
        public ActionResult TetsModel()
        {
            var obj=new Models.StudentInfo
                {
                Id="123",
                Name="Nguyen Ngoc Duy",
                Mark="7"
            };
            
            return View(obj);
        }
        public ActionResult TestListModel()
        {
            
            return View(lst);
        }
        public ActionResult Create() 
            {
                return View();
            }
        public ActionResult Edit(string Id)
        {
            var obj=lst.FirstOrDefault(x => x.Id==Id);
            return View(obj);
        }
        [HttpPost]
        public ActionResult Login(string Taikhoan)
        {
            Session["User"] =Taikhoan;
            return RedirectToAction("TestListModel");
        }
    }
}

WebApplication3/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebApplication3.Controllers
{
    public class ProductController : Controller
    {
        public static List<Models.Product> lst = new List<Models.Product>();
        // GET: Product
        public ActionResult Index()
        {
            return View(lst);
        }
        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Create(Models.Product obj)
        {
            obj.Id="1";
            if (obj.Sale == 0)
            {
                obj.PriceSale=obj.Price;
            }
            else
            {
                obj.PriceSale=obj.Price - obj.Price * obj.Sale /100;
            }
            
            var fAvatar = Request.Files["fImage"];
            if (fAvatar != null)
            {
                // nếu có file được chọn => upload len server
                string fileName = fAvatar.FileName;// tự sinh tên file
                /* string fileName = DateTime.Now.ToString("yyyy/MM/dd");*/
                string folderPath = Server.MapPath("~/Asset/upload/"+fileName);
                fAvatar.SaveAs(folderPath);
                obj.Image="/Asset/upload/" + fileName;
            }
            lst.Add(obj);

            return RedirectToAction("Index");
            /*  return View();*/
        }
    }
}

WebApplication3/Controllers/StudentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebApplication3.Controllers
{
    //viết thêm phần quản lý đăng nhập
  /*  [Authorize]*/
    public class StudentController : Controller
    {
        

        public static List<Models.StudentInfo> lst=new List<Models.StudentInfo>();
        // GET: Student
      /*  [AllowAnonymous]*/
        public ActionResult Index()
        {
            foreach (var item in lst)
            {
                Console.WriteLine(item.Name);
            }
            return View(lst);
        }
        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Create(Models.StudentInfo obj)
        {
            obj.Id="1";
            var fAvatar = Request.Files["fAvatar"];
            if(fAvatar != null)
            {
                // nếu có file được chọn => upload len server
                string fileName = fAvatar.FileName;// tự sinh tên file
                /* string fileName = DateTime.Now.ToString("yyyy/MM/dd");*/
                string folderPath=Server.MapPath("~/Asset/upload/"+fileName);
                fAvatar.SaveAs(folderPath);
                obj.Avatar="/Asset/upload/" + fileName;
            }
            lst.Add(obj);
           
             return RedirectToAction("Index");
          /*  return View();*/
        }
    }
}

WebApplication3/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<main aria-labelledby="title">
    <h2 id="title">@ViewBag.Title.</h2>
    <h3>@ViewBag.Message</h3>

    <p>Use this area to provide additional information.</p>
</main>

WebApplication3/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<main aria-labelledby="title">
    <h2 id="title">@ViewBag.Title.</h2>
    <h3>@ViewBag.Message</h3>

    <address>
        One Microsoft Way<br />
        Redmond, WA 98052-6399<br />
        <abbr title="Phone">P:</abbr>
        425.555.0100
    </address>

    <address>
        <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
        <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
    </address>
</main>

WebApplication3/Views/Home/Create.cshtml
@model WebApplication3.Models.StudentInfo

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>
@using (Html.BeginForm())
{
    @*<div>
        @Html.LabelFor(m => m.Id)
        @Html.TextBoxFor(m => m.Id)
    </div>
    <div>
        @Html.LabelFor(m => m.Pwd)
        @Html.PasswordFor(m => m.Pwd)
    </div>
    <div>
        @Html.LabelFor(m => m.Name)
        @Html.TextBoxFor(m => m.Name)
    </div>
    <div>
        @Html.LabelFor(m => m.BirthDay)
        @Html.TextBoxFor(m => m.BirthDay)
    </div>
    <div>
        @Html.LabelFor(m => m.Mark)
        @Html.TextBoxFor(m => m.Mark)
    </div>
    <div>
        @Html.LabelFor(m => m.Note)
        @Html.EditorFor(m => m.Note)
    </div>*@
    @Html.EditorForModel()
}

WebApplication3/Views/Home/Edit.cshtml
@model WebApplication3.Models.StudentInfo

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>
@using (Html.BeginForm())
{
    <div>
       
        @Html.HiddenFor(m => m.Id)
    </div>
    <div>
        @Html.LabelFor(m => m.Pwd)
        @Html.PasswordFor(m => m.Pwd)
    </div>
    <div>
        @Html.LabelFor(m => m.Name)
        @Html.TextBoxFor(m => m.Name)
    </div>
    <div>
        @Html.LabelFor(m => m.Mark)
        @Html.TextBoxFor(m => m.Mark)
    </div>

}

WebApplication3/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<main>
    <section class="row" aria-labelledby="aspnetTitle">
        <h1 id="title">ASP.NET</h1>
        <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
        <p><a href="https://asp.net" class="btn btn-primary btn-md">Learn more &raquo;</a></p>
    </section>

    <div class="row">
        <section class="col-md-4" aria-labelledby="gettingStartedTitle">
            <h2 id="gettingStartedTitle">Getting started</h2>
            <p>
                ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
                enables a clean separation of concerns and gives you full control over markup
                for enjoyable, agile development.
            </p>
            <p><a class="btn btn-outline-dark" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
        </section>
        <section class="col-md-4" aria-labelledby="librariesTitle">
            <h2 id="librariesTitle">Get more libraries</h2>
            <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
            <p><a class="btn btn-outline-dark" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
        </section>
        <section class="col-md-4" aria-labelledby="hostingTitle">
            <h2 id="hostingTitle">Web Hosting</h2>
            <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
            <p><a class="btn btn-outline-dark" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
        </section>
    </div>
</main>

WebApplication3/Views/Home/Login.cshtml
@{ 
    var number= 123456.8765;
}
<p>
    Đơn giá là : @Html.FormatValue(number,"{0:#,###.##0}")
</p>
<h2>Login</h2>
<div>
    @using(Html.BeginForm())
    {
        <label>Quyền truy cập</label>
        @Html.DropDownList("Roles","Lựa chọn quyền truy cập")
    }
</div>
    

WebApplication3/Views/Home/Test.cshtml
@{
    ViewBag.Title = "Test";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Test</h2>

<h3>Welcome to D16CNPM6</h3>

WebApplication3/Views/Home/TestListModel.cshtml
@model  List<WebApplication3.Models.StudentInfo>

@{
    ViewBag.Title = "TestListModel";
}

<h2>TestListModel</h2>

<h2>View @Session["User"]</h2>
<table>
    <tr>
        <th>ID</th>
        <th>Name</th>
        <th>Mark</th>
    </tr>
    @{
        for (int i = 0; i<Model.Count; i++)
        {
            <tr>
                <td>@Model[i].Id</td>
                <td>@Model[i].Name</td>
                <td>@Model[i].Mark</td>
                <td>@Html.ActionLink("Chỉnh sửa","Edit",new { id = Model[i].Id })</td>
            </tr>
        }
    }
</table>

WebApplication3/Views/Home/TestModel.cshtml
@model WebApplication3.Models.StudentInfo
@{
    ViewBag.Title = "TestModel";
}

<h2>TestModel</h2>

<ul>
    <li>@Model.Id </li>
    <li>@Model.Name</li>
    <li>@Model.Mark</li>
</ul>

WebApplication3/Views/Product/Create.cshtml
@model WebApplication3.Models.Product

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm("Create", "Product", FormMethod.Post, new { @enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>StudentInfo</h4>
    <hr />
    @*        @Html.ValidationSummary(true, "", new { @class = "text-danger" })*@
    @*  @Html.HiddenFor(model => model.Id)*@
    <div class="form-group">
        @Html.LabelFor(model => model.Id, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Id, new { htmlAttributes = new { @class = "form-control" } })
            @*   @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })*@
        </div>
    </div>


    <div class="form-group">
        @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
            @*   @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })*@
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Image, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @*            @Html.EditorFor(model => model.Avatar, new { htmlAtutributes = new { @class = "form-control" } })*@
            <input type="file" name="fImage" />
            @*  @Html.ValidationMessageFor(model => model.Avatar, "", new { @class = "text-danger" })*@
        </div>
    </div>



    <div class="form-group">
        @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
            @*  @Html.ValidationMessageFor(model => model.Mark, "", new { @class = "text-danger" })*@
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Sale, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Sale, new { htmlAttributes = new { @class = "form-control" } })
            @*    @Html.ValidationMessageFor(model => model.Note, "", new { @class = "text-danger" })*@
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.Star, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Star, new { htmlAttributes = new { @class = "form-control" } })
            @*    @Html.ValidationMessageFor(model => model.Note, "", new { @class = "text-danger" })*@
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-default" />
        </div>
    </div>
</div>
}

WebApplication3/Views/Product/Index.cshtml
@model  List<WebApplication3.Models.Product>


<!doctype html>
<html lang="en">

<head>
    <title>Title</title>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <style>
        .hover {
            display: none;
            position: absolute;
            background-color: rgba(255, 255, 255, 0.5);
            width: 200px;
            height: 400px;
        }

        .card {
            overflow: hidden;
        }

        .product:hover .hover {
            display: block;
        }

        .btnshop {
            background-color: rgb(250, 107, 107);
            color: white;
            padding: 5px;
            border-radius: 10px;
            left: 50%;
            top: 50%;
            position: absolute;
            transform: translate(-50%, -50%);
        }
        .color-star {
            color: rgb(255,132,24);
        }
        .sale {
            margin-top: 10px;
            position: absolute;
            color: white;
            background-color: rgb(255,132,24);
            padding-right: 15px;
            padding-left: 10px;
            border-end-end-radius: 10px;
            border-top-right-radius: 10px;
        }
    </style>
</head>

<body>
    <div class="container-fluid">
        <div class="row d-flex justify-content-center p-2">

            <button class="btn btn-danger font-weight-bold ml-3">LASTEST</button>
            <button class="btn  font-weight-bold ml-3"> @Html.ActionLink("FEATURED", "Create")</button>
            <button class="btn  font-weight-bold ml-3">SPECIAL</button>
        </div>
        <div class="row">
            @{
                for (int i = 0; i<Model.Count; i++)
                {
                    <div class="col-lg-2 product">
                                    <div class="card">
                                        <img class="card-img-top" src="@Model[i].Image"
                                             alt="Card image cap">
                                        <div class="card-body">
                                            <p class="card-text">@Model[i].Name</p>
                                            
                                            <div class="d-flex">
                                                <h6 class="card-title mr-2">$ @Model[i].PriceSale</h6>
                                                @{
                                                    if (Model[i].Sale !=0)
                                                    {
                                                        <h6 class="card-title text-danger"> <del>$ @Model[i].Price</del> </h6>
                                                    }
                                                }
                                                
                                            </div>
                                            @{
                                                for (int j = 0; j<5; j++)
                                                {
                                                    if (j<Model[i].Star)
                                                    {
                                                        <span><i class="fa-solid fa-star color-star"></i></span>
                                                    }
                                                    else
                                                    {
                                                        <span><i class="fa-solid fa-star"></i></span>
                                                    }
                                                }
                                            }
                                        </div>
                                        <div class="hover">
                                            <a href="#" class="btnshop btn">SOLD OUT</a>
                                        </div>
                                        @{
                                            if (Model[i].Sale !=0)
                                            {
                                                <div class="sale">
                                                    <span>SALE</span>
                                                </div>
                                            }
                                        }

                                    </div>
                    </div>

                    }
                }

            </div>
    </div>
  
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
            integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
            crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
            integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
            crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
            integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
            crossorigin="anonymous"></script>
</body>

</html>

WebApplication3/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark">
        <div class="container">
            @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" title="Toggle navigation" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li>@Html.ActionLink("Home", "Index", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("About", "About", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

WebApplication3/Views/Student/Create.cshtml
@model WebApplication3.Models.StudentInfo

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm("Create","Student",FormMethod.Post,new {@enctype="multipart/form-data"}))
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>StudentInfo</h4>
    <hr />
    @*        @Html.ValidationSummary(true, "", new { @class = "text-danger" })*@
    @*  @Html.HiddenFor(model => model.Id)*@
    <div class="form-group">
        @Html.LabelFor(model => model.Id, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Id, new { htmlAttributes = new { @class = "form-control" } })
            @*   @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })*@
        </div>
    </div>


    <div class="form-group">
        @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
            @*   @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })*@
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.Pwd, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Pwd, new { htmlAttributes = new { @class = "form-control" } })
            @*   @Html.ValidationMessageFor(model => model.Pwd, "", new { @class = "text-danger" })*@
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.Avatar, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @*            @Html.EditorFor(model => model.Avatar, new { htmlAtutributes = new { @class = "form-control" } })*@
            <input type="file" name="fAvatar" />
            @*  @Html.ValidationMessageFor(model => model.Avatar, "", new { @class = "text-danger" })*@
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.BirthDay, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.BirthDay, new { htmlAttributes = new { @class = "form-control" } })
            @*  @Html.ValidationMessageFor(model => model.BirthDay, "", new { @class = "text-danger" })*@
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Mark, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Mark, new { htmlAttributes = new { @class = "form-control" } })
            @*  @Html.ValidationMessageFor(model => model.Mark, "", new { @class = "text-danger" })*@
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Note, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Note, new { htmlAttributes = new { @class = "form-control" } })
            @*    @Html.ValidationMessageFor(model => model.Note, "", new { @class = "text-danger" })*@
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

WebApplication3/Views/Student/Index.cshtml
@model  List<WebApplication3.Models.StudentInfo>

@{
    ViewBag.Title = "Index";
}
<style>
    table {
        border-collapse: collapse;
        border: solid 1px black;
    }
    table th, table td {
        border: solid 1px black;
        padding: 10px;
    }
</style>
<div>
    @Html.ActionLink("Thêm mới","Create")
</div>

<h2>TestListModel</h2>

<h2>View @Session["User"]</h2>
<table>
    <tr>
        <th>@Html.DisplayNameFor(m => m[0].Id)</th>
        <th>@Html.DisplayNameFor(m => m[0].Avatar)</th>
        <th>@Html.DisplayNameFor(m => m[0].Name)</th>
        <th>@Html.DisplayNameFor(m => m[0].BirthDay)</th>
        <th>@Html.DisplayNameFor(m => m[0].Mark)</th>
        <th>@Html.DisplayNameFor(m => m[0].Note)</th>
    </tr>
    @{
        for (int i = 0; i<Model.Count; i++)
        {
        <tr>
            <td>@Model[i].Id</td>
            <td><img src="@Model[i].Avatar" width="100px" />   </td>
            <td>@Model[i].Name</td>
            <td>@Html.FormatValue(@Model[i].BirthDay,"{0:dd/MM/yyyy}")</td>
            <td>@Model[i].Mark</td>
            <td>@Model[i].Note</td>

            <td>@Html.ActionLink("Chỉnh sửa", "Edit", new { id = Model[i].Id })</td>
        </tr>
        }
    }
</table>

WebApplication3/Views/View.cshtml
@model  List<WebApplication3.Models.StudentInfo>

@{
    ViewBag.Title = "View";
}

<h2>View</h2>
<table>
    <tr>
        <th>ID</th>
        <th>Name</th>
        <th>Mark</th>
    </tr>
    @{ 
        for(int i = 0; i<Model.Count; i++)
            {
                <tr>
                    <td>@Model[i].Id</td>
                    <td>@Model[i].Name</td>
                    <td>@Model[i].Mark</td>
                </tr>
            }
    }
</table>